name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Pack
      run: |
        cd Strato.Analyzers
        dotnet pack --configuration Release /p:NuspecFile=Strato.Analyzers.nuspec
        
    - name: Deploy
      run: dotnet nuget push ./Strato.Analyzers/bin/Release/*.nupkg --skip-duplicate --api-key ${{ NUGET_API_KEY }}
